## Bitnami PostgreSQL image version
## ref: https://hub.docker.com/r/bitnami/postgresql/tags/
##
image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 16.1.0-debian-11-r25

## PostgreSQL user (has superuser privileges if username is `postgres`)
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
postgresqlUsername: postgres

# initdb scripts
# Specify dictionary of scripts to be run at first boot
# Alternatively, you can put your scripts under the files/docker-entrypoint-initdb.d directory
#
initdbScripts:
  util_functions.sql: |
    -- Функция для создания пользователя, если нет
    CREATE OR REPLACE FUNCTION create_user_if_not_exists(username TEXT, password TEXT) 
    RETURNS void AS $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = username) THEN
            EXECUTE format('CREATE USER %I WITH PASSWORD %L', username, password);
            RAISE NOTICE 'User % created', username;
        ELSE
            RAISE NOTICE 'User % already exists', username;
        END IF;
    END;
    $$ LANGUAGE plpgsql;

# PostgreSQL password using existing secret
existingSecret: postgresql-credentials

persistence:
  size: 100Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 256Mi
