name: "openid_connect"
label: "SSO"
args:
  client_options:
    identifier: "gitlab"
    secret: "Yztbr7ZwqSIf8Twf34JrC3t1NA0Z50Bt"
    redirect_uri: "https://gitlab.local/users/auth/openid_connect/callback"
    authorization_endpoint: "https://keycloak.local/realms/master/protocol/openid-connect/auth"
    token_endpoint: "http://keycloak-keycloakx-headless.keycloak.svc.cluster.local:8080/realms/master/protocol/openid-connect/token"
    userinfo_endpoint: "http://keycloak-keycloakx-headless.keycloak.svc.cluster.local:8080/realms/master/protocol/openid-connect/userinfo"
    jwks_uri: http://keycloak-keycloakx-headless.keycloak.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs
  discovery: false
  issuer: "https://keycloak.local/realms/master"
  scope: ["openid", "profile", "email"]
