## Overrides the default args for the Keycloak container
args:
  - start

# Additional environment variables for Keycloak
extraEnv: |
  - name: KC_HOSTNAME
    value: "keycloak.local"
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: "admin"
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    value: "admin"

# Pod resource requests and limits
resources: {}
  # requests:
  #   cpu: "500m"
  #   memory: "1024Mi"
  # limits:
  #   cpu: "500m"
  #   memory: "1024Mi"

ingress:
  # If `true`, an Ingress is created
  enabled: true
  # The name of the Ingress Class associated with this ingress
  ingressClassName: nginx
  # List of rules for the Ingress
  rules:
    -
      # Ingress host
      host: keycloak.local
      # Paths for the host
      paths:
        - path: /
          pathType: Prefix
  # TLS configuration
  tls:
   - hosts:
       - keycloak.local
     secretName: wildcard-local-tls

database:
  # don't create secret for db password. Instead use existing k8s secret
  # existingSecret: "my-existent-dbpass-secret"
  # existingSecretKey: "password"
  existingSecret: postgresql-secret
  existingSecretKey: password
  # E.g. dev-file, dev-mem, mariadb, mssql, mysql, oracle or postgres
  vendor: postgres
  hostname: postgresql.postgresql.svc.cluster.local
  port: 5432
  database: keycloak
  username: keycloak

cache:
  # Use "custom" to disable automatic cache configuration
  stack: default

proxy:
  enabled: true
  mode: xforwarded
  http:
    enabled: true

metrics:
  enabled: false

health:
  enabled: false

http:
  # For backwards compatibility reasons we set this to the value used by previous Keycloak versions.
  relativePath: /
  internalPort: http-internal
  internalScheme: HTTP
