resources-template: &resources-template
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 128Mi


ingress:
  apiServer:
    enabled: true
    hosts:
      - name: airflow.local
        tls:
          enabled: true
          secretName: wildcard-local-tls
    ingressClassName: nginx
  flower:
    enabled: true
    hosts:
      - name: flower.local
        tls:
          enabled: true
          secretName: wildcard-local-tls
    ingressClassName: nginx

data:
  metadataSecretName: external-postgresql-secret

databaseCleanup:
  enabled: true
  retentionDays: 90

workers:
  # Resource configuration for Airflow Celery workers and pods created with pod-template-file
  <<: *resources-template

scheduler:
  <<: *resources-template

apiServer:
  <<: *resources-template
  # Example: To enable proxy headers support when running behind a reverse proxy:
  args: ["bash", "-c", "exec airflow api-server --proxy-headers"]
  # Example: To configure FORWARDED_ALLOW_IPS when running behind a reverse proxy:
  env:
    - name: FORWARDED_ALLOW_IPS
      value: "*"  # Use "*" for trusted environments, or specify proxy IP ranges for production

webserver:
  <<: *resources-template

triggerer:
  <<: *resources-template

secret:
  - envName: "AIRFLOW_CONN_GITLAB" 
    secretName: "airflow-dags-gitlab-connection"
    secretKey: "GITLAB_CONN_JSON"

dagProcessor:
  <<: *resources-template
  dagBundleConfigList:
    - name: gitlab
      classpath: "airflow.providers.git.bundles.git.GitDagBundle"
      kwargs:
        git_conn_id: "gitlab" # airflow найдет его через AIRFLOW_CONN_GITLAB
        tracking_ref: "main"
        refresh_interval: 60

flower:
  <<: *resources-template
  enabled: true

statsd:
  enabled: false

redis:
  <<: *resources-template

postgresql:
  enabled: false

config:
  secrets:
    backend: airflow.providers.hashicorp.secrets.vault.VaultBackend
    backend_kwargs: '{"connections_path": "connections", "mount_point": "airflow", "url": "http://vault-internal.vault.svc.cluster.local:8200", "auth_type": "kubernetes", "kubernetes_role": "airflow-role", "auth_mount_point": "kubernetes"}'
  # KeycloakAuthManager https://airflow.apache.org/docs/apache-airflow-providers-keycloak/stable/auth-manager/setup/config.html#configure-airflow-to-use-the-keycloak-auth-manager
  core:
    auth_manager: airflow.providers.keycloak.auth_manager.keycloak_auth_manager.KeycloakAuthManager
  keycloak_auth_manager:
    server_url: http://keycloak-keycloakx-headless.keycloak.svc.cluster.local:8080
    realm: master
    client_id: airflow
    # Get from keycloak client id credentials
    client_secret:
    
# Only for dev mode
extraEnv: |
  - name: _PIP_ADDITIONAL_REQUIREMENTS
    value: "apache-airflow-providers-keycloak==0.8.1"
