injector:
  # True if you want to enable vault agent injection.
  # @default: global.enabled
  enabled: false

server:  
  ingress:
    enabled: true
    # Optionally use ingressClassName instead of deprecated annotation.
    # See: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
    ingressClassName: nginx
    hosts:
      - host: vault.local
    tls:
      - secretName: wildcard-local-tls
        hosts:
          - vault.local

  extraSecretEnvironmentVars:
    - envName: VAULT_TOKEN
      secretName: vault-root-token
      secretKey: VAULT_ROOT_TOKEN
    - envName: VAULT_UNSEAL_KEY_1
      secretName: vault-unseal-keys
      secretKey: VAULT_UNSEAL_KEY_1
    - envName: VAULT_UNSEAL_KEY_2
      secretName: vault-unseal-keys
      secretKey: VAULT_UNSEAL_KEY_2
    - envName: VAULT_UNSEAL_KEY_3
      secretName: vault-unseal-keys
      secretKey: VAULT_UNSEAL_KEY_3

  postStart:
    - /bin/sh
    - -c
    - |
      sleep 5;
      for i in $(seq 1 30); do
        vault status >/dev/null 2>&1;
        [ $? -ne 1 ] && break;
        sleep 2;
      done;
      vault operator unseal "$VAULT_UNSEAL_KEY_1" >/dev/null 2>&1;
      vault operator unseal "$VAULT_UNSEAL_KEY_2" >/dev/null 2>&1;
      vault operator unseal "$VAULT_UNSEAL_KEY_3" >/dev/null 2>&1;
      
      vault write auth/kubernetes/config \
        kubernetes_host="https://kubernetes.default.svc:443" \
        kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
        token_reviewer_jwt=@/var/run/secrets/kubernetes.io/serviceaccount/token;

      echo 'path "airflow/data/connections/*" {
        capabilities = ["read", "list"]
      }' | vault policy write airflow-policy -;

      vault write auth/kubernetes/role/airflow-role \
        bound_service_account_names="airflow-worker,airflow-scheduler,airflow-api-server" \
        bound_service_account_namespaces="airflow" \
        policies="airflow-policy";

      vault kv put airflow/connections/pg_default conn_type="postgres" host="postgresql.postgresql.svc.cluster.local" database="postgres" login="postgres" password="postgres" port="5432";

  standalone:
    enabled: true

    # config is a raw string of default configuration when using a Stateful
    # deployment. Default is to use a PersistentVolumeClaim mounted at /vault/data
    # and store data there. This is only used when using a Replica count of 1, and
    # using a stateful set. Supported formats are HCL and JSON.

    # Note: Configuration files are stored in ConfigMaps so sensitive data
    # such as passwords should be either mounted through extraSecretEnvironmentVars
    # or through a Kube secret. For more information see:
    # https://developer.hashicorp.com/vault/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations
    config: |-
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
      }
      
      storage "file" {
        path = "/vault/data"
      }
