# JDBC datasource settings. Only required when using JDBC version store type; ignored otherwise.
jdbc:
  # -- The JDBC connection string. If you are using Nessie OSS images, then only
  # PostgreSQL, MariaDB and MySQL URLs are supported. Check your JDBC driver documentation
  # for the correct URL format.
  jdbcUrl: jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/nessie
  secret:
    # -- The secret name to pull datasource credentials from.
    name: postgresql-secret
    # -- The secret key storing the datasource username.
    username: username
    # -- The secret key storing the datasource password.
    password: password

# -- The Nessie catalog server configuration.
catalog:

  # -- Whether to enable the REST catalog service.
  enabled: true

  # -- Iceberg catalog settings.
  iceberg:

    # -- The default warehouse name. Required. This is just a symbolic name; it must refer to a
    # declared warehouse below.
    defaultWarehouse: iceberg

    # -- Iceberg config defaults applicable to all clients and warehouses. Any properties that are
    # common to all iceberg clients should be included here. They will be passed to all clients on
    # all warehouses as config defaults. These defaults can be overridden on a per-warehouse basis,
    # see below.
    configDefaults: {}
    # io-impl: org.apache.iceberg.hadoop.HadoopFileIO

    # -- Iceberg config overrides applicable to all clients and warehouses. Any properties that are
    # common to all iceberg clients should be included here. They will be passed to all clients on
    # all warehouses as config overrides. These overrides can be overridden on a per-warehouse
    # basis, see below.
    configOverrides: {}
    # s3.acl: public-read-write

    # -- Iceberg warehouses. Each warehouse is a location where Iceberg tables are stored. Each
    # warehouse has a name, a location, and optional config defaults and overrides. At least one
    # warehouse must be defined.
    warehouses:
      # -- Symbolic name of the warehouse. Required.
    - name: iceberg
      # -- Location of the warehouse. Required. Used to determine the base location of a table.
      # Scheme must be either s3 (Amazon S3), gs (Google GCS) or abfs / abfss (Azure ADLS). Storage
      # properties for each location can be defined below.
      location: s3://iceberg/
      # -- Iceberg config defaults specific to this warehouse. They override any defaults specified
      # above in catalog.iceberg.configDefaults.
      configDefaults: {}
      # -- Iceberg config overrides specific to this warehouse. They override any defaults specified
      # above in catalog.iceberg.configOverrides.
      configOverrides: {}
    # In rare cases it might be legit to turn off the object-stores readiness check.
    objectStoresHealthCheckEnabled: true

  # -- Catalog storage settings.
  storage:
    s3:

      # Global S3 settings. Can be overridden on a per-bucket basis below.
      defaultOptions:
        # -- DNS name of the region, required for AWS.
        region: us-east-1
        # -- Endpoint URI, required for private clouds. Optional; if not provided, the default is
        # used.
        endpoint: http://minio.minio.svc.cluster.local:9000
        # -- Whether to use path-style access. Optional; if not provided, the default is used. If
        # true, path-style access will be used, as in: https://<domain>/<bucket>. If false, a
        # virtual-hosted style will be used instead, as in: https://<bucket>.<domain>.
        pathStyleAccess: true
        # -- Controls the authentication mode for the Catalog server. Valid values are:
        # - APPLICATION_GLOBAL: Use the default AWS credentials provider chain.
        # - STATIC: Static credentials provided through the accessKeySecret option.
        # The default is STATIC.
        authType: STATIC
        # -- AWS credentials. Required when serverAuthenticationMode is STATIC.
        accessKeySecret:
          # -- The secret name to pull AWS credentials from.
          name: warehouse-secret
          # -- The secret key storing the AWS secret key id.
          awsAccessKeyId: access-key-id
          # -- The secret key storing the AWS secret access key.
          awsSecretAccessKey: secret-access-key-id

# -- Advanced configuration.
# You can pass here any valid Nessie or Quarkus configuration property.
# Any property that is defined here takes precedence over all the other configuration values generated by this chart.
# Properties can be passed "flattened" or as nested YAML objects (see examples below).
advancedConfig:
  nessie.catalog.service.s3.default-options.chunked-encoding-enabled: false
# -- Advanced configuration via Environment Variables.
# Extra environment variables to add to the Nessie server container.
# You can pass here any valid EnvVar object:
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#envvar-v1-core
# This can be useful to get configuration values from Kubernetes secrets or config maps.
extraEnv:
  []
#  - name: QUARKUS_MONGODB_APPLICATION_NAME
#    value: my-app
#  - name: QUARKUS_MONGODB_TLS
#    valueFrom:
#      configMapKeyRef:
#        name: mongodb-config
#        key: tls

metrics:
  # -- Specifies whether metrics for the nessie server should be enabled.
  enabled: false

serviceMonitor:
  # -- Specifies whether a ServiceMonitor for Prometheus operator should be created.
  enabled: false


# -- Nessie Ingress settings.
# These settings generate an Ingress resource that routes external traffic to the Nessie service.
# Consider enabling sticky sessions based on the remote client's IP address;
# this is generally beneficial to Nessie deployments, but some testing may be
# required in order to make sure that the load is distributed evenly among the pods.
# Check your ingress controller's documentation.
ingress:
  # -- Specifies whether an ingress should be created.
  enabled: true
  # -- Specifies the ingressClassName; leave empty if you don't want to customize it.
  className: nginx
  # -- Specifies the path type of host paths. Valid values are: "Prefix", "Exact" or "ImplementationSpecific".
  pathType: Prefix
  # -- A list of host paths used to configure the ingress.
  hosts:
    - host: nessie.local
      paths:
        - /
  # -- A list of TLS certificates; each entry has a list of hosts in the certificate,
  # along with the secret name used to terminate TLS traffic on port 443.
  tls:
   - hosts:
      - nessie.local
     secretName: wildcard-local-tls

# -- Configures the resources requests and limits for nessie pods.
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
